apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: basic-k8s-demo
  labels:
    app: kuard
spec:
  replicas: 5
  selector:
    matchLabels: 
      name: kuard
  template:
    metadata:
      labels:
        app: kuard
        name: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
        resources:
          requests:
            memory: "20Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
      restartPolicy: Always