apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: basic-k8s-demo
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:blue
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
    - containerPort: 8082